# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

variables:
  GAUGE_TELEMETRY_ENABLED: false

jobs:
- job: MacOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      echo installing gauge
      brew install gauge
    displayName: 'install gauge'

  - script: |
      echo starting gauge test
      ./gradlew clean gauge
    displayName: 'gauge test'

- job: Linux

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: |
      echo installing gauge
      sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
      echo deb https://dl.bintray.com/gauge/gauge-deb nightly main | sudo tee -a /etc/apt/sources.list
      sudo apt-get update
      sudo apt-get install gauge
    displayName: 'install gauge'

  - script: |
      echo starting gauge test
      ./gradlew clean gauge
    displayName: 'gauge test'

- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'

    - powershell: |
        echo installing gauge
        npm install -g npm@latest
        npm install -g @getgauge/cli
      displayName: 'install gauge'

    - powershell: |
        echo starting gauge test
        ./gradlew.bat clean gauge
      displayName: 'gauge test'